theme: osuny
_merge: deep
params:
  breadcrumb:
    position: after-hero
  summary:
    position: hero
  search:
    active: true
  logo:
    header: ''
    footer: ''
  home:
    head:
      title: site
  organizations:
    single:
      backlinks: true
  projects:
    index:
      layout: list
      options:
        categories: true
        image: true
        subtitle: true
        summary: true
        year: true
      truncate_description: 0
